import { Category } from "../db/schema";

export const topicToCategory: Record<string, Category> = {
    productivity: "productivity",
    todo: "productivity",
    "todo-list": "productivity",
    "task-manager": "productivity",
    "note-taking": "productivity",
    notes: "productivity",
    calendar: "productivity",
    pomodoro: "productivity",
    "tab-manager": "productivity",
    "bookmark-manager": "productivity",
  
    devtools: "developer_tools",
    "developer-tools": "developer_tools",
    "dev-tools": "developer_tools",
    debugging: "developer_tools",
    "web-development": "developer_tools",
    "json-viewer": "developer_tools",
    "react-devtools": "developer_tools",
    "vue-devtools": "developer_tools",
    "api-testing": "developer_tools",
    "code-formatter": "developer_tools",
  
    chat: "communication",
    messaging: "communication",
    email: "communication",
    slack: "communication",
    discord: "communication",
    notifications: "communication",
  
    design: "design",
    css: "design",
    "color-picker": "design",
    figma: "design",
    "ui-design": "design",
    font: "design",
    screenshot: "design",
    "image-editor": "design",
  
    finance: "finance",
    crypto: "finance",
    cryptocurrency: "finance",
    budget: "finance",
    "expense-tracker": "finance",
    stock: "finance",
    trading: "finance",
    wallet: "finance",
  
    security: "security",
    privacy: "security",
    "password-manager": "security",
    encryption: "security",
    vpn: "security",
    "ad-blocker": "security",
    adblocker: "security",
    "tracker-blocker": "security",
  
    education: "education",
    learning: "education",
    dictionary: "education",
    "language-learning": "education",
    translator: "education",
    translation: "education",
    flashcards: "education",
  
    entertainment: "entertainment",
    video: "entertainment",
    streaming: "entertainment",
    music: "entertainment",
    youtube: "entertainment",
    gaming: "entertainment",
  
    social: "social",
    "social-media": "social",
    twitter: "social",
    reddit: "social",
    "social-network": "social",
  
    utility: "utilities",
    utilities: "utilities",
    clipboard: "utilities",
    "download-manager": "utilities",
  }; /// kayaknya perlu di pindah ke file yang lain